name: final_project_news_app
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.0 <4.0.0'
  
dependencies:
  firebase_core: ^2.15.0
  firebase_crashlytics: ^3.3.4
  comment_box: ^0.0.18
  flutter:
    sdk: flutter
  cloud_firestore: ^4.8.5
  firebase_auth: ^4.7.3
  flutter_facebook_auth: ^6.0.1
  google_sign_in: ^6.1.4
  firebase_storage: ^11.2.6
  shared_preferences: ^2.2.0
  provider: ^6.0.5
  firebase_messaging: ^14.6.7
  after_layout: ^1.2.0
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/bottoms/
    - assets/icons/
    - assets/homes/
    - assets/person/